import { defineConfig } from 'astro/config';
import react from '@astrojs/react';
import tailwind from '@astrojs/tailwind';

// https://astro.build
export default defineConfig({
  site: 'https://melissacolin.ai',
  output: 'static',
  trailingSlash: 'never',
  build: { format: 'directory' },
  i18n: {
    locales: ['fr', 'en'],
    defaultLocale: 'fr',
    routing: { prefixDefaultLocale: false },
  },
  integrations: [
    react(),
    // Tailwind 3 via the legacy integration; we keep our own @tailwind directives
    // and global rules in src/index.css, so don't inject Astro's base styles.
    tailwind({ applyBaseStyles: false }),
    // Sitemap is generated by a custom endpoint (src/pages/sitemap.xml.ts) in Phase 4
    // for full control over i18n + hreflang.
  ],
  vite: {
    resolve: {
      alias: {
        '@': '/src',
        '@components': '/src/components',
        '@data': '/src/data',
        '@utils': '/src/utils',
      },
    },
  },
});
